baseURL = 'https://Astreonix.github.io/my-portfolio/'
languageCode = 'en-us'
title = 'Mehr Ali | AI Engineer'
theme = 'blowfish'
relativeURLs = true

[markup.goldmark.renderer]
    unsafe = true

# This tells Hugo to look in your config folder
config = ["config/_default/config.toml", "config/_default/languages.toml", "config/_default/menus.toml", "config/_default/params.toml"]